---
deployment:
  tasks:
    - export DEPLOYPATH=/home/xyz1/public_html/27cbd448b7e30e3661a25592f3db9cb8/festplayer/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp getid3 $DEPLOYPATH
    - /bin/cp audio.min.js $DEPLOYPATH
    - /bin/cp audiojs.swf $DEPLOYPATH
    - /bin/cp festi.png $DEPLOYPATH
    - /bin/cp getsongs.js $DEPLOYPATH
    - /bin/cp getsongs.php $DEPLOYPATH
    - /bin/cp home.png $DEPLOYPATH
    - /bin/cp player-graphics.gif $DEPLOYPATH
    - /bin/cp selectsongs.js $DEPLOYPATH
    - /bin/cp simplebar.css $DEPLOYPATH
    - /bin/cp simplebar.js $DEPLOYPATH